"""Initial migration

Revision ID: 46787cece54e
Revises: 
Create Date: 2026-05-11 18:54:24.835716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '46787cece54e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('clean_word_count', sa.Integer(), nullable=False),
    sa.Column('n_chunks', sa.Integer(), nullable=False),
    sa.Column('suspect_count', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_id'), 'checks', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('text_len', sa.Integer(), nullable=False),
    sa.Column('clean_word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('check_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('matched_document_id', sa.Integer(), nullable=True),
    sa.Column('matched_filename', sa.String(length=255), nullable=False),
    sa.Column('matched_year', sa.Integer(), nullable=True),
    sa.Column('matched_query_chunks', sa.Integer(), nullable=False),
    sa.Column('matched_corpus_chunks', sa.Integer(), nullable=False),
    sa.Column('n_query_chunks', sa.Integer(), nullable=False),
    sa.Column('n_corpus_chunks', sa.Integer(), nullable=False),
    sa.Column('overlap_query', sa.Float(), nullable=False),
    sa.Column('overlap_corpus', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_similarity', sa.Float(), nullable=False),
    sa.Column('mean_top_similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_matches_check_id'), 'check_matches', ['check_id'], unique=False)
    op.create_index(op.f('ix_check_matches_id'), 'check_matches', ['id'], unique=False)
    op.create_index(op.f('ix_check_matches_matched_document_id'), 'check_matches', ['matched_document_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_idx', sa.Integer(), nullable=False),
    sa.Column('token_start', sa.Integer(), nullable=False),
    sa.Column('token_end', sa.Integer(), nullable=False),
    sa.Column('text_preview', sa.String(length=1024), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.create_table('document_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_document_texts_id'), 'document_texts', ['id'], unique=False)
    op.create_table('check_match_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_match_id', sa.Integer(), nullable=False),
    sa.Column('query_chunk_idx', sa.Integer(), nullable=False),
    sa.Column('corpus_chunk_idx', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('query_token_start', sa.Integer(), nullable=True),
    sa.Column('query_token_end', sa.Integer(), nullable=True),
    sa.Column('corpus_token_start', sa.Integer(), nullable=True),
    sa.Column('corpus_token_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_match_id'], ['check_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_match_chunks_check_match_id'), 'check_match_chunks', ['check_match_id'], unique=False)
    op.create_index(op.f('ix_check_match_chunks_id'), 'check_match_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_match_chunks_id'), table_name='check_match_chunks')
    op.drop_index(op.f('ix_check_match_chunks_check_match_id'), table_name='check_match_chunks')
    op.drop_table('check_match_chunks')
    op.drop_index(op.f('ix_document_texts_id'), table_name='document_texts')
    op.drop_table('document_texts')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_check_matches_matched_document_id'), table_name='check_matches')
    op.drop_index(op.f('ix_check_matches_id'), table_name='check_matches')
    op.drop_index(op.f('ix_check_matches_check_id'), table_name='check_matches')
    op.drop_table('check_matches')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_checks_id'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###
