"""add_unique_constraint_to_document

Revision ID: 5dc5fe7e8c51
Revises: 46787cece54e
Create Date: 2026-05-11 20:57:31.927910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc5fe7e8c51'
down_revision: Union[str, Sequence[str], None] = '46787cece54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_filename_year', 'documents', ['filename', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_filename_year', 'documents', type_='unique')
    # ### end Alembic commands ###
